name: Container teste
on: 
    workflow_dispatch:  

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Exec do runner
              run: cat /etc/os-release
            - name: Exec no Container
              uses: docker://alpine:latest
              with:
                entrypoint: cat
                args: /etc/os-release

